import type { Metadata } from "next";
import "./globals.css";
import Footer from "./_components/shared components/Footer";
import WhatsAppButton from "./_components/shared components/WhatsAppBtn";


export const metadata: Metadata = {
  title: "Trio - Marketing Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <Footer/>
        <WhatsAppButton/>
      </body>
    </html>
  );
}
