import type { Metadata } from "next";
// Removed Geist font imports; using Inter via globals.css
import "./globals.css";

// Removed Geist font setup

export const metadata: Metadata = {
  title: "Trio - Marketing Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
